---
# Tasks file for the Serverspec role

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install ruby
  ansible.builtin.dnf:
    name: ruby
    state: present

- name: Install Serverspec
  community.general.gem:
    name: "{{ item }}"
    executable: /usr/bin/gem
    user_install: false
  with_items:
    - rake
    - serverspec

- name: Mount NFS share
  ansible.posix.mount:
    path: /mnt
    src: localhost:/nfs
    fstype: nfs
    opts: nfsvers=3
    state: mounted

- name: Run Serverspec tests
  ansible.builtin.shell: /bin/bash -lc "cd serverspec && /usr/local/bin/rake"
  register: result
  changed_when: result.rc != 0

- name: Unmount NFS share
  ansible.posix.mount:
    path: /mnt
    state: unmounted
