# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'almalinux/9'
  config.vm.provider 'libvirt' do |vb|
    vb.memory = 2048
    vb.cpus = 8
  end
  config.vm.provision "shell", inline: <<-SHELL
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/YumaYX/init/main/init.sh)"
  SHELL
end

