---
- name: Check Env.
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if the system is virtualized
      ansible.builtin.command: bash -lc "systemd-detect-virt"
      register: virt_check
      ignore_errors: true
      failed_when: false

- name: Init
  hosts: all
  vars:
    prime_user: user
    ruby_version: 4.0.0
  roles:
    - init
    - console
    - workspace
    - user
    - homebrew
    #- rust
    - rust-dnf
    - ruby
    - ys1
    - httpd
    - samba
    #- rear
    - role: kvm
      when: virt_check.stdout == "none"
      ignore_errors: true
    - role: code
      when: virt_check.stdout == "none"
      ignore_errors: true
    - role: more
      ignore_errors: true
    - serverspec
