- hosts: all
  gather_facts: no
  tasks:
    - name: Check if the system is virtualized
      shell: bash -lc "systemd-detect-virt"
      register: virt_check
      ignore_errors: yes

- hosts: all
  vars:
    prime_user: yuma
    ruby_version: 3.3.5
  roles:
    - init
    - user
    - ruby
    - httpd
    - nfs
    - workspace
    - serverspec
    - role: kvm-vagrant
      when: virt_check.stdout == "none"
