---
# tasks file for roles/pxe

######################## tftpd
- name: Install tftp-server
  ansible.builtin.dnf:
    name: tftp-server
    state: latest

- name: Up tftp-server
  ansible.builtin.systemd_service:
    name: tftp
    state: restarted
    enabled: true

- name: install firewalld
  ansible.builtin.dnf:
    name: "firewalld"
    state: present

- name: start firewalld
  ansible.builtin.systemd_service:
    name: "firewalld"
    enabled: yes
    state: started

- name: firewalld for tftp
  ansible.posix.firewalld:
    service: tftp
    permanent: true
    state: enabled

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded

# ######################## dhcpd
- name: Install dhcp-server
  ansible.builtin.dnf:
    name: dhcp-server
    state: latest

- name: dhcpd.conf
  template:
    src: templates/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf

- name: firewalld for dhcp
  ansible.posix.firewalld:
    service: dhcp
    permanent: true
    state: enabled

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: Up dhcp-server
  ansible.builtin.systemd_service:
    name: dhcpd
    state: restarted
    enabled: true

# ######################## tftpd cfg

- name: kickstart directory created
  file:
    path: "/tmp/rpm"
    state: directory

# - name: reinst shim grub
#   ansible.builtin.dnf:
#     name: "{{ packages }}"
#     download_only: yes
#     download_dir: "/tmp/rpm"
#     state: present
#   vars:
#     packages:
#     - shim
#     - grub2-efi-x64

- name : install rpm2cpio shim-x64-*.rpm
  shell: "dnf -y reinstall --downloadonly --downloaddir=/tmp/rpm shim grub2-efi-x64"
- name : rpm2cpio shim-x64-*.rpm
  shell: bash -lc "cd /tmp/rpm && rpm2cpio shim-x64-*.rpm | cpio -dimv"
- name : rpm2cpio grub2-efi-x64-*.rpm
  shell: bash -lc "cd /tmp/rpm && rpm2cpio grub2-efi-x64-*.rpm | cpio -dimv"

- name: copy BOOTX64.EFI
  copy:
    src: /tmp/rpm/boot/efi/EFI/BOOT/BOOTX64.EFI
    dest: /var/lib/tftpboot/BOOTX64.EFI
    mode: '0644'
    force: yes

- name: copy grubx64.efi
  copy:
    src: "/tmp/rpm/boot/efi/EFI/almalinux/grubx64.efi"
    dest: /var/lib/tftpboot/grubx64.efi
    force: yes
    mode: '0644'
    # need change dir name by distribution

- name: Download iso
  ansible.builtin.get_url:
    url: https://ftp.riken.jp/Linux/almalinux/9.3/isos/x86_64/AlmaLinux-9-latest-x86_64-minimal.iso
    dest: /tmp/linux9.iso

- name: kickstart directory created
  file:
    path: "/var/pxe/linux9"
    state: directory

- name: Mount DVD read-only
  ansible.posix.mount:
    src: /tmp/linux9.iso
    path: /var/pxe/linux9
    fstype: iso9660
    opts: loop,ro
    state: mounted

- name: kickstart directory created
  file:
    path: "/var/lib/tftpboot/linux9"
    state: directory

- name: copy vmlinuz
  copy:
    src: /var/pxe/linux9/images/pxeboot/vmlinuz
    dest: /var/lib/tftpboot/linux9
    force: yes

- name: copy initrd.img
  copy:
    src: /var/pxe/linux9/images/pxeboot/initrd.img
    dest: /var/lib/tftpboot/linux9
    force: yes

- name: copy grub.cfg
  template:
    src: templates/grub.cfg.j2
    dest: /var/lib/tftpboot/grub.cfg

##################### httpd
- name: pxeboot.conf
  template:
    src: templates/pxeboot.conf.j2
    dest: /etc/httpd/conf.d/pxeboot.conf

- name: Restart httpd service
  ansible.builtin.systemd_service:
    name: httpd
    state: restarted
    enabled: true
    daemon_reload: true

- name: kickstart directory created
  file:
    path: "/var/www/html/ks"
    state: directory

- name: ks.cfg
  template:
    src: templates/ks.cfg.j2
    dest: /var/www/html/ks/ks.cfg

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
