---
# Tasks file for the workspace role
- name: Ensure necessary directories exist
  file:
    path: "/work/{{ item }}"
    state: directory
    recurse: yes
  loop:
    - lib
    - data
    - output
    - downloads
    - sandbox

