---
# Tasks file for the workspace role
- name: Ensure necessary directories exist
  file:
    path: "/work/{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ prime_user }}"
    group: "{{ prime_user }}"
    mode: '0755'
  loop:
    - lib
    - data
    - output
    - downloads
    - sandbox

