---
# tasks file for roles/code
- name: Add Visual Studio Code repository
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install VSCode
  ansible.builtin.dnf:
    name: code
    state: present
