---
# tasks file for roles/httpd

- name: firewalld for http
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: install httpd
  ansible.builtin.dnf:
    name: httpd
    state: latest

- name: Restart httpd service
  ansible.builtin.systemd_service:
    name: httpd
    state: restarted
    enabled: true
    daemon_reload: true

