---
# tasks file for roles/init
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: install tools
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - vim
    - make
    - "@development"
    - "@Server with GUI"

- name: install firewalld
  ansible.builtin.dnf:
    name: "firewalld"
    state: present

- name: start firewalld
  ansible.builtin.systemd_service:
    name: "firewalld"
    enabled: yes
    state: started

- name: set hostname
  ansible.builtin.hostname:
    name: y.localdomain

- name: Create user
  user:
    name: "{{ prime_user }}"
    shell: /bin/bash

- name: sudo
  template:
    src: templates/sudo.j2
    dest: /etc/sudoers.d/{{ prime_user }}

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "/home/{{ prime_user }}/.ssh"
    state: directory
    owner: "{{ prime_user }}"
    group: "{{ prime_user }}"
    mode: '0700'
 
- name: Check if SSH key exists 
  stat:
    path: "/home/{{ prime_user }}/.ssh/id_ed25519"
  register: file_status

- name: Generate ED25519 SSH key
  ansible.builtin.openssh_keypair:
    path: "/home/{{ prime_user }}/.ssh/id_ed25519"
    type: ed25519
    passphrase: ""
  become: yes
  become_user: "{{ prime_user }}"
  when: not file_status.stat.exists

- name: Change Keys Owner
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ prime_user }}"
    group: "{{ prime_user }}"
    mode: '0600'
  with_items:
    - "/home/{{ prime_user }}/.ssh/id_ed25519"
    - "/home/{{ prime_user }}/.ssh/id_ed25519.pub"

- name: git clone
  ansible.builtin.git:
    repo: https://github.com/YumaYX/dotfiles.git
    dest: /home/{{ prime_user }}/dotfiles
  become: yes
  become_user: "{{ prime_user }}"

- name: Run 'install' target as {{ prime_user }}
  community.general.make:
    chdir: /home/{{ prime_user }}/dotfiles
    target: install
  become: yes
  become_user: "{{ prime_user }}"

