---
# tasks file for roles/init
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: install tools
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - vim
    - make
    - "@development"
    - "@Server with GUI"

- name: install firewalld
  ansible.builtin.dnf:
    name: "firewalld"
    state: present

- name: start firewalld
  ansible.builtin.systemd_service:
    name: "firewalld"
    enabled: yes
    state: started

- name: set hostname
  ansible.builtin.hostname:
    name: x.y

- name: Create user
  user:
    name: "{{ prime_user }}"
    shell: /bin/bash

- name: sudo
  template:
    src: templates/sudo.j2
    dest: /etc/sudoers.d/{{ prime_user }}

- name: git clone
  ansible.builtin.git:
    repo: https://github.com/YumaYX/dotfiles.git
    dest: /home/{{ prime_user }}/dotfiles
  become: yes
  become_user: "{{ prime_user }}"

- name: Run 'install' target as {{ prime_user }}
  community.general.make:
    chdir: /home/{{ prime_user }}/dotfiles
    target: install
  become: yes
  become_user: "{{ prime_user }}"

