---
# tasks file for roles/init
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: dnf update - cron
  ansible.builtin.cron:
    name: "dnf-update-cron"
    minute: "0"
    job: "dnf -y update"

- name: install tools
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - vim
    - make
    - "@development"
    - "@Server with GUI"

- name: install firewalld
  ansible.builtin.dnf:
    name: "firewalld"
    state: present

- name: start firewalld
  ansible.builtin.systemd_service:
    name: "firewalld"
    enabled: yes
    state: started

- name: set hostname
  ansible.builtin.hostname:
    name: y.localdomain

