---
# tasks file for roles/ruby
- name: Ensure CRB repository is enabled
  shell: bash -lc "dnf config-manager --set-enabled crb"

- name: Install necessary packages for Ruby
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - bzip2
      - gcc
      - openssl-devel
      - readline-devel
      - zlib-devel
      - libyaml-devel
      - git

- name: sudo
  template:
    src: templates/ruby.j2
    dest: /etc/sudoers.d/ruby

- name: Check Ruby Install
  shell: bash -lc "ruby -v"
  ignore_errors: yes
  register: command_result

- name: Download
  ansible.builtin.get_url:
    url: "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-{{ ruby_version }}.tar.gz"
    dest: "/tmp/ruby-{{ ruby_version }}.tar.gz"
  when: "('ruby ' + ruby_version) not in command_result.stdout"

- name: Extract
  ansible.builtin.unarchive:
    src: "/tmp/ruby-{{ ruby_version }}.tar.gz"
    dest: /tmp
  when: "('ruby ' + ruby_version) not in command_result.stdout"

- name: Configure
  shell: bash -lc "cd /tmp/ruby-{{ ruby_version }} && ./configure"
  when: "('ruby ' + ruby_version) not in command_result.stdout"

- name: make
  make:
    chdir: "/tmp/ruby-{{ ruby_version }}"
  when: "('ruby ' + ruby_version) not in command_result.stdout"

- name: make install
  make:
    chdir: "/tmp/ruby-{{ ruby_version }}"
    target: install
  become: yes
  when: "('ruby ' + ruby_version) not in command_result.stdout"

- name: Update Gems system
  shell: bash -lc "/usr/local/bin/gem update --system"

- name: Update Gems
  shell: bash -lc "/usr/local/bin/gem update"

- name: Install necessary gems
  gem:
    name: "{{ item }}"
    executable: /usr/local/bin/gem
    user_install: false
  with_items:
    - minitest
    - rake
    - roo
    - rubocop
    - serverspec

- name: gem update - cron
  ansible.builtin.cron:
    name: "gem-update-cron"
    minute: "30"
    job: "gem update --system && gem update"

