---
# tasks file for roles/ruby
- name: Ensure CRB repository is enabled
  shell: bash -lc "dnf config-manager --set-enabled crb"

- name: Install necessary packages for Ruby
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - bzip2
      - gcc
      - openssl-devel
      - readline-devel
      - zlib-devel
      - libyaml-devel
      - git

- name: sudo
  template:
    src: templates/ruby.j2
    dest: /etc/sudoers.d/ruby

- name: Download
  ansible.builtin.get_url:
    url: "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-{{ ruby_version }}.tar.gz"
    dest: "/tmp/ruby-{{ ruby_version }}.tar.gz"
- name: Extract
  ansible.builtin.unarchive:
    src: "/tmp/ruby-{{ ruby_version }}.tar.gz"
    dest: /tmp
- name: configure
  shell: bash -lc "cd /tmp/ruby-{{ ruby_version }} && ./configure"
- name: Build the default target
  make:
    chdir: "/tmp/ruby-{{ ruby_version }}"
- name: Run 'install' target as root
  make:
    chdir: "/tmp/ruby-{{ ruby_version }}"
    target: install
  become: yes

- name: Update Gems system
  shell: bash -lc "gem update --system"

- name: Update Gems
  shell: bash -lc "gem update"

- name: Install necessary gems
  gem:
    name: "{{ item }}"
    executable: /usr/local/bin/gem
  with_items:
    - minitest
    - rake
    - roo
    - rubocop
    - serverspec

- name: gem update - cron
  ansible.builtin.cron:
    name: "gem-update-cron"
    minute: "30"
    job: "gem update --system && gem update"

